### ISSUE TITLE
Is it possible to run it in an RaspberryPi?

### ISSUE THREAD

**Issue by pechex** [quarckster/conkodi#1]
Arch in RPI is ARM64 so I guess this won't work. I don't know much about docker, but can it be done?

**Comment by quarckster** [comment]
I guess I can build this image for a different arch. I just don't know if this PPA https://launchpad.net/~team-xbmc has aarch64 repo.

**Comment by quarckster** [comment]
It seems Kodi PPA doesn't work on arm64 https://forum.kodi.tv/showthread.php?tid=362374&pid=3034106#pid3034106
